name: Deploy to Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H 45.56.74.113 >> ~/.ssh/known_hosts
        shell: bash

      - name: Deploy files
        run: |
          #clean up old tarbells on server
          ssh cameron@45.56.74.113 "rm -f /var/www/bluTape/server/deploy.tar.gz"

          # Pack your server files (adjust path if needed)
          tar --exclude='env' --exclude='__pycache__' --exclude='*.pyc' --exclude='.git' --exclude='deploy.tar.gz' -czf deploy.tar.gz -C server .

          #Use scp to copy the archive to server
          scp deploy.tar.gz cameron@45.56.74.113:/var/www/blutape.net/server/

          #deploy react build to server
          cd client
          npm ci
          npm run build
          scp -r dist/* cameron@45.56.74.113:/var/www/blutape.net/client/dist/

        shell: bash

      - name: SSH into server and restart app
        run: |
          ssh cameron@45.56.74.113 'deploy'
        shell: bash
